/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans:    ['DM Sans', 'system-ui', 'sans-serif'],
        display: ['Bricolage Grotesque', 'system-ui', 'sans-serif'],
        mono:    ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      colors: {
        primary:              "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary:            "hsl(var(--secondary))",
        "secondary-foreground":"hsl(var(--secondary-foreground))",
        background:           "hsl(var(--background))",
        foreground:           "hsl(var(--foreground))",
        muted:                "hsl(var(--muted))",
        "muted-foreground":   "hsl(var(--muted-foreground))",
        card:                 "hsl(var(--card))",
        "card-foreground":    "hsl(var(--card-foreground))",
        border:               "hsl(var(--border))",
        input:                "hsl(var(--input))",
        ring:                 "hsl(var(--ring))",
        destructive:          "hsl(var(--destructive))",
        sidebar:              "hsl(var(--sidebar))",
        "sidebar-border":     "hsl(var(--sidebar-border))",
        "sidebar-foreground": "hsl(var(--sidebar-foreground))",
        "sidebar-muted":      "hsl(var(--sidebar-muted))",
        "sidebar-accent":     "hsl(var(--sidebar-accent))",
      },
      borderRadius: {
        lg:  "var(--radius)",
        md:  "calc(var(--radius) - 2px)",
        sm:  "calc(var(--radius) - 4px)",
        xl:  "calc(var(--radius) + 4px)",
        "2xl":"calc(var(--radius) + 8px)",
      },
      boxShadow: {
        card:  "0 1px 3px 0 rgb(0 0 0 / 0.06), 0 1px 2px -1px rgb(0 0 0 / 0.04)",
        "card-hover": "0 4px 16px -2px rgb(0 0 0 / 0.10), 0 2px 6px -2px rgb(0 0 0 / 0.06)",
        modal: "0 20px 60px -10px rgb(0 0 0 / 0.25), 0 8px 24px -6px rgb(0 0 0 / 0.12)",
        "btn":  "0 1px 2px 0 rgb(0 0 0 / 0.08)",
        "btn-hover": "0 3px 8px -1px rgb(0 0 0 / 0.14), 0 1px 3px -1px rgb(0 0 0 / 0.08)",
      },
    },
  },
  plugins: [],
};
